const menu = [{
    id: 1,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/maggi.jpg?raw=true",
    name: "maggi",
    category: "breakfast",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
   
},
{
    id: 2,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/allupakoida.jpg?raw=true",
    name: "pakoda",
    category: "evening",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
{
    id: 3,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/chola.jpg?raw=true",
    name: "chola",
    category: "lunch",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
{
    id: 4,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/momo.jpg?raw=true",
    name: "momo",
    category: "evening",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
{
    id: 5,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/paubhaji.jpg?raw=true",
    name: "pavbhaji",
    category: "dinner",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
{
    id: 6,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/pizza.jpg?raw=true",
    name: "pizza",
    category: "breakfast",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
{
    id: 7,
    image : "https://github.com/thapatechnical/reactjsByThapaTechnical/blob/main/public/images/rajmarice.jpg?raw=true",
    name: "rajmarice",
    category: "lunch",
    price: 25,
    description : " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem voluptates, corporis enim impedit quam harum ducimus ullam dolores iste maiores quaerat velit reiciendis quae accusantium. Odit eligendi aut molestias unde.",
},
];

export default menu;